"""empty message

Revision ID: 649ab12c86da
Revises: 
Create Date: 2022-07-07 13:45:45.637867

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '649ab12c86da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('src_station', sa.String(length=100), nullable=True),
    sa.Column('dest_station', sa.String(length=100), nullable=True),
    sa.Column('created_ts', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('generated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sendings',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('order_id', postgresql.UUID(), nullable=False),
    sa.Column('dest_station', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sendings')
    op.drop_table('orders')
    # ### end Alembic commands ###
